#!/bin/bash

# base file name for skin package
PACKAGE_NAME=enchanted_elves

# PS client installation paths to copy skin to
DEPLOY_PATHS="${HOME}/opt/PlaneShift/art/skins \
			 ${HOME}/build/planeshift/planeshift/art/skins"

# XSD schema to validate skin files
SCHEMA="pst/schema/paws-core-auto-1.0.xsd"

# command to do validation against XSD schema
VALIDATE_CMD="xmllint --noout --schema"

# XSL transformation from PAWS to HTML 
TRANSFORM="pst/xslt/default.xslt"

# command to do XSL transformation
TRANSFORM_CMD="xsltproc --novalid -o"
