#!/bin/bash

source ./pst-params

if (( $# > 0 ))
then
	FILES_TO_VALIDATE=$@
else
	FILES_TO_VALIDATE=$(find . -name "*.xml" -and \! -name "_*.xml" )
fi

# validate all XML files
for xml_file in ${FILES_TO_VALIDATE} ; do
	$VALIDATE_CMD ${SCHEMA} "${xml_file}"
done

